### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by np22-jpg** [intelligent-agent/revolve#4]
I see that the files haven't been updated for over 4 months now. Is the project dead?

**Comment by eliasbakken** [comment]
Not at all, but there have been some delays due to the delivery of the
previous Kickstarter and making the pre production batch. I made a board a
couple of days ago to get started with making a testing jig for it.

**Comment by marcboivin** [comment]
Glad to hear it. Good luck with the progress. Can't wait to get my hand on one!
